### ISSUE TITLE
Special Charset

### ISSUE THREAD

**Issue by ferhat37ozkan** [fiqrisr/bulk-certificate-generator#1]
Hello, there is an issue. I tried Turkish Charsets, set new font but nothing happened. its look like FERHAT Ã–ZKAN but it must be FERHAT ÖZKAN how can i solve it?

thanks best regards.

**Comment by RioChndr** [comment]
Hello, i'm not owner this project, but I try to look to this problem.
I found out that your font has unique encoding, and this project use PIL as library to generate text and image. By default PIL use unicode encoding. you need to try another text encoding manually at [ImageFont.trueType() line code](https://github.com/fiqrisr/bulk-certificate-generator/blob/10680881903bd0f213a30aa98dcc9850fb1c9ed2/image_drawer.py#L6), you can see antoher encoding type at [PIL Documentation](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.truetype)

for example apply **symb** unicode, so you need to modify [image_drawer.py](https://github.com/fiqrisr/bulk-certificate-generator/blob/10680881903bd0f213a30aa98dcc9850fb1c9ed2/image_drawer.py#L6) like this

`font = ImageFont.truetype(font, font_size, encoding="symb")`

Hope this solve your problem.

**Comment by ferhat37ozkan** [comment]
> Hello, i'm not owner this project, but I try to look to this problem.
> I found out that your font has unique encoding, and this project use PIL as library to generate text and image. By default PIL use unicode encoding. you need to try another text encoding manually at [ImageFont.trueType() line code](https://github.com/fiqrisr/bulk-certificate-generator/blob/10680881903bd0f213a30aa98dcc9850fb1c9ed2/image_drawer.py#L6), you can see antoher encoding type at [PIL Documentation](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.truetype)
> 
> for example apply **symb** unicode, so you need to modify [image_drawer.py](https://github.com/fiqrisr/bulk-certificate-generator/blob/10680881903bd0f213a30aa98dcc9850fb1c9ed2/image_drawer.py#L6) like this
> 
> `font = ImageFont.truetype(font, font_size, encoding="symb")`
> 
> Hope this solve your problem.

Hello, I tried it but still same. nothing happened. :(
